# Generated by Django 5.2.5 on 2025-08-12 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_cart_product_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_ordered', models.BooleanField(default=False)),
                ('cart_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
                ('product_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('wishlist_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.wishlist')),
            ],
        ),
    ]
